server:
  port: 8012
spring:
  application:
    name: PhotoAppApiConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Christopher-OOC/PhotoAppConfigServer
          username: Christopher-OOC
          password:
          defaultLabel: main
          cloneOnStart: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: busrefresh
