server:
  port: 8012
spring:
  application:
    name: PhotoAppApiConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Christopher-OOC/PhotoAppConfiguration.git
          skipSslValidation: true
          cloneOnStart: true
