server:
  port: 8012
spring:
  application:
    name: PhotoAppApiConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Christopher-OOC/PhotoAppConfiguration.git
          username: Christopher-OOC
          password: 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
          cloneOnStart: true
          defaultLabel: main