server:
  port: 8012
spring:
  application:
    name: PhotoAppApiConfigServer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Christopher-OOC/PhotoAppConfigServer
          username: Christopher-OOC
          password: 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
          defaultLabel: main
          cloneOnStart: true
management:
  endpoints:
    web:
      exposure:
        include: busrefresh
